name: New FXserver version released
on:
  workflow_dispatch:
    inputs:
      optional:
        description: 'new optional version'
        required: false
      recommended:
        description: 'new recommended version'
        required: false
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo "recommended=${{ github.event.inputs.recommended }}, optional=${{ github.event.inputs.optional }}"
